name: Avalanche TraderJoe Leverage Strategy
on:
  pull_request:
    paths:
      - ".github/workflows/avalanche-traderjoe-leverage.yml"
      - ".github/actions/setup-env/action.yml"
      - "vesper-commons/utils/setup.js"
      - "vesper-pools/contracts/pool/**/*.sol"
      - "vesper-pools/contracts/pool/*.sol"
      - "vesper-strategies/contracts/strategies/Strategy.sol"
      - "vesper-strategies/contracts/strategies/compound/avalanche/TraderJoeLeverage.sol"
      - "vesper-strategies/contracts/strategies/compound/avalanche/CompoundLikeLeverage.sol"
      - "vesper-strategies/contracts/strategies/compound/CompoundLeverageBase.sol"
      - "vesper-strategies/contracts/AvalancheFlashLoanHelper.sol"
      - "vesper-strategies/test/behavior/compound-leverage.js"
      - "vesper-strategies/test/avalanche/traderjoe/leverage/*.js"

# Limit concurrency to one workflow per branch and one per pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  setup-job:
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.AVALANCHE_NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

  vaavax-test:
    needs: [setup-job]
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.AVALANCHE_NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Running TraderJoe Leverage strategy for VAAVAX pool
        run: npm test -- --scope vesper-strategies -- test/avalanche/traderjoe/leverage/vaavax.spec.js

  vadaie-test:
    needs: [setup-job]
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.AVALANCHE_NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Running TraderJoe Leverage strategy for VADAIe pool
        run: npm test -- --scope vesper-strategies -- test/avalanche/traderjoe/leverage/vadaie.spec.js

  vausdc-test:
    needs: [setup-job]
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.AVALANCHE_NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Running TraderJoe Leverage strategy for VAUSDC pool
        run: npm test -- --scope vesper-strategies -- test/avalanche/traderjoe/leverage/vausdc.spec.js

  vausdce-test:
    needs: [setup-job]
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.AVALANCHE_NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Running TraderJoe Leverage strategy for VAUSDCe pool
        run: npm test -- --scope vesper-strategies -- test/avalanche/traderjoe/leverage/vausdce.spec.js

  vawbtce-test:
    needs: [setup-job]
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.AVALANCHE_NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Running TraderJoe Leverage strategy for VAWBTCe pool
        run: npm test -- --scope vesper-strategies -- test/avalanche/traderjoe/leverage/vawbtce.spec.js

  vawethe-test:
    needs: [setup-job]
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.AVALANCHE_NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Running TraderJoe Leverage strategy for VAWETHe pool
        run: npm test -- --scope vesper-strategies -- test/avalanche/traderjoe/leverage/vawethe.spec.js
