name: Mainnet Compound Xy Strategy
on:
  pull_request:
    paths:
      - ".github/workflows/mainnet-compound-xy.yml"
      - ".github/actions/setup-env/action.yml"
      - "vesper-commons/utils/setup.js"
      - "vesper-strategies/test/behavior/compound-xy.js"
      - "vesper-strategies/test/behavior/vesper-compound-xy.js"
      - "vesper-pools/contracts/pool/**/*.sol"
      - "vesper-pools/contracts/pool/*.sol"
      - "vesper-strategies/contracts/strategies/Strategy.sol"
      - "vesper-strategies/contracts/strategies/compound/CompoundXy*"
      - "vesper-strategies/contracts/strategies/compound/CompoundVesperXy*"
      - "vesper-strategies/test/mainnet/compound/xy/**/*.js"

# Limit concurrency to one workflow per branch and one per pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  setup-job:
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

  vaeth-test:
    needs: [setup-job]
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Running Compound XY strategy for VAETH pool
        run: npm test -- --scope vesper-strategies -- test/mainnet/compound/xy/vaeth.spec.js

  vawbtc-test:
    needs: [setup-job]
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Running Compound XY strategy for VAWBTC pool
        run: npm test -- --scope vesper-strategies -- test/mainnet/compound/xy/vawbtc.spec.js

  vaeth-vesper-test:
    needs: [setup-job]
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Running Compound Vesper XY strategy for VAETH pool
        run: npm test -- --scope vesper-strategies -- test/mainnet/compound/xy/vesper/vaeth.spec.js

  vawbtc-vesper-test:
    needs: [setup-job]
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Running Compound Vesper XY strategy for VAWBTC pool
        run: npm test -- --scope vesper-strategies -- test/mainnet/compound/xy/vesper/vawbtc.spec.js

  vadai-vesper-test:
    needs: [setup-job]
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Running Compound Vesper XY strategy for VADAI pool
        run: npm test -- --scope vesper-strategies -- test/mainnet/compound/xy/vesper/vadai.spec.js
