name: Mainnet Aave Strategy
on:
  pull_request:
    paths:
      - ".github/workflows/mainnet-aaveV2.yml"
      - ".github/actions/setup-env/action.yml"
      - "vesper-commons/utils/setup.js"
      - "vesper-pools/contracts/pool/**/*.sol"
      - "vesper-pools/contracts/pool/*.sol"
      - "vesper-strategies/contracts/strategies/Strategy.sol"
      - "vesper-strategies/contracts/strategies/aave/v2/AaveV2Core.sol"
      - "vesper-strategies/contracts/strategies/aave/v2/AaveV2.sol"
      - "vesper-strategies/test/mainnet/aave/**"
# Limit concurrency to one workflow per branch and one per pull_request.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  setup-job:
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

  vadai-test:
    needs: [setup-job]
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Running Aave strategy for VADAI pool
        run: npm test -- --scope vesper-strategies -- test/mainnet/aave/v2/vadai.spec.js

  vauni-test:
    needs: [setup-job]
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Running Aave strategy for VAUNI pool
        run: npm test -- --scope vesper-strategies -- test/mainnet/aave/v2/vauni.spec.js

  vausdc-test:
    needs: [setup-job]
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Running Aave strategy for VAUSDC pool
        run: npm test -- --scope vesper-strategies -- test/mainnet/aave/v2/vausdc.spec.js

  vausdt-test:
    needs: [setup-job]
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Running Aave strategy for VAUSDT pool
        run: npm test -- --scope vesper-strategies -- test/mainnet/aave/v2/vausdt.spec.js
