name: Mainnet AaveV2 Leverage Strategy
on:
  pull_request:
    paths:
      - ".github/workflows/mainnet-aaveV2-leverage.yml"
      - ".github/actions/setup-env/action.yml"
      - "vesper-commons/utils/setup.js"
      - "vesper-pools/contracts/pool/**/*.sol"
      - "vesper-pools/contracts/pool/*.sol"
      - "vesper-strategies/contracts/strategies/Strategy.sol"
      - "vesper-strategies/contracts/FlashLoanHelper.sol"
      - "vesper-strategies/contracts/strategies/aave/v2/AaveV2Core.sol"
      - "vesper-strategies/contracts/strategies/aave/v2/AaveLeverageStrategy.sol"
      - "vesper-strategies/test/mainnet/aave/v2/leverage/*.js"
      - "vesper-strategies/test/behavior/aave-leverage.js"
# Limit concurrency to one workflow per branch and one per pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  setup-job:
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

  vadai-test:
    needs: [setup-job]
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Running AaveV2 leverage strategy for VADAI pool
        run: npm test -- --scope vesper-strategies -- test/mainnet/aave/v2/leverage/vadai.spec.js
