name: Mainnet Alpha Homora Strategy
on:
  pull_request:
    paths:
      - ".github/workflows/mainnet-alpha.yml"
      - ".github/actions/setup-env/action.yml"
      - "vesper-commons/test/utils/setup.js"
      - "vesper-pools/contracts/pool/**/*.sol"
      - "vesper-pools/contracts/pool/*.sol"
      - "vesper-strategies/contracts/strategies/Strategy.sol"
      - "vesper-strategies/contracts/strategies/alpha/AlphaHomora.sol"
      - "vesper-strategies/contracts/strategies/alpha/AlphaHomoraETH.sol"
      - "vesper-strategies/test/mainnet/alpha/*.js"

# Limit concurrency to one workflow per branch and one per pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  setup-job:
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

  vadpi-test:
    needs: [setup-job]
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Running Alpha Homora strategy for VADPI pool
        run: npm test -- --scope vesper-strategies -- test/mainnet/alpha/vadpi.spec.js

  vaeth-test:
    needs: [setup-job]
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Running Alpha Homora strategy for VAETH pool
        run: npm test -- --scope vesper-strategies -- test/mainnet/alpha/vaeth.spec.js

  vausdc-test:
    needs: [setup-job]
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Running Alpha Homora strategy for VAUSDC pool
        run: npm test -- --scope vesper-strategies -- test/mainnet/alpha/vausdc.spec.js
