name: Mainnet Euler Xy Strategy
on:
  pull_request:
    paths:
      - ".github/workflows/mainnet-euler-xy.yml"
      - ".github/actions/setup-env/action.yml"
      - "vesper-commons/utils/setup.js"
      - "vesper-strategies/test/behavior/euler-vesper-xy.js"
      - "vesper-pools/contracts/pool/**/*.sol"
      - "vesper-pools/contracts/pool/*.sol"
      - "vesper-strategies/contracts/strategies/Strategy.sol"
      - "vesper-strategies/contracts/strategies/euler/EulerXy.sol"
      - "vesper-strategies/contracts/strategies/euler/EulerVesperXy.sol"
      - "vesper-strategies/test/mainnet/euler/xy/**/*.js"

# Limit concurrency to one workflow per branch and one per pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  setup-job:
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

  vaeth-vesper-test:
    needs: [setup-job]
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Running Euler Vesper XY strategy for VAETH pool
        run: npm test -- --scope vesper-strategies -- test/mainnet/euler/xy/vesper/vaeth.spec.js

  vausdc-vesper-test:
    needs: [setup-job]
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Running Euler Vesper XY strategy for VAUSDC pool
        run: npm test -- --scope vesper-strategies -- test/mainnet/euler/xy/vesper/vausdc.spec.js

  vadai-vesper-test:
    needs: [setup-job]
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Running Euler Vesper XY strategy for VADAI pool
        run: npm test -- --scope vesper-strategies -- test/mainnet/euler/xy/vesper/vadai.spec.js

  vacbeth-vesper-test:
    needs: [setup-job]
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Running Euler Vesper XY strategy for VACBETH pool
        run: npm test -- --scope vesper-strategies -- test/mainnet/euler/xy/vesper/vacbeth.spec.js