name: Mainnet Vesper Strategy
on:
  pull_request:
    paths:
      - ".github/workflows/mainnet-vesper.yml"
      - ".github/actions/setup-env/action.yml"
      - "vesper-commons/utils/setup.js"
      - "vesper-pools/contracts/pool/**/*.sol"
      - "vesper-pools/contracts/pool/*.sol"
      - "vesper-strategies/contracts/strategies/Strategy.sol"
      - "vesper-strategies/contracts/strategies/Earn.sol"
      - "vesper-strategies/contracts/strategies/vesper/Vesper.sol"
      - "vesper-strategies/contracts/strategies/vesper/earn/VesperEarn.sol"
      - "vesper-strategies/contracts/strategies/vesper/earn/VesperEarnSaddleLp.sol"

# Limit concurrency to one workflow per branch and one per pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  setup-job:
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

  earn-vafrax-fraxbp-test:
    needs: [setup-job]
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Running Earn Vesper FRAX FRAXBP strategy
        run: npm test -- --scope vesper-strategies -- test/mainnet/vesper/earn/frax-fraxbp.spec.js
