name: Mainnet FraxLend Xy Strategy
on:
  pull_request:
    paths:
      - ".github/workflows/mainnet-frax-lend-xy.yml"
      - ".github/actions/setup-env/action.yml"
      - "vesper-commons/utils/setup.js"
      - "vesper-strategies/test/behavior/frax-lend-vesper-xy.js"
      - "vesper-pools/contracts/pool/**/*.sol"
      - "vesper-pools/contracts/pool/*.sol"
      - "vesper-strategies/contracts/strategies/Strategy.sol"
      - "vesper-strategies/contracts/strategies/frax-lend/FraxLendVesperXy.sol"
      - "vesper-strategies/test/mainnet/frax-lend/xy/**/*.js"

# Limit concurrency to one workflow per branch and one per pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  setup-job:
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

  vaeth-vesper-test:
    needs: [setup-job]
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Running FraxLend Vesper XY strategy for VAETH pool
        run: npm test -- --scope vesper-strategies -- test/mainnet/frax-lend/xy/vesper/vaeth.spec.js

  vawbtc-vesper-test:
    needs: [setup-job]
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Running FraxLend Vesper XY strategy for VAWBTC pool
        run: npm test -- --scope vesper-strategies -- test/mainnet/frax-lend/xy/vesper/vawbtc.spec.js
