name: Optimism Sonne Xy Strategy
on:
  pull_request:
    paths:
      - ".github/workflows/optimism-sonne-xy.yml"
      - ".github/actions/setup-env/action.yml"
      - "vesper-commons/utils/setup.js"
      - "vesper-strategies/test/behavior/compound-xy.js"
      - "vesper-strategies/test/behavior/vesper-compound-xy.js"
      - "vesper-pools/contracts/pool/**/*.sol"
      - "vesper-pools/contracts/pool/*.sol"
      - "vesper-strategies/contracts/strategies/Strategy.sol"
      - "vesper-strategies/contracts/strategies/compound/CompoundXy*"
      - "vesper-strategies/contracts/strategies/compound/CompoundVesperXy*"
      - "vesper-strategies/contracts/strategies/compound/optimism/SonneVesperXy.sol"
      - "vesper-strategies/test/optimism/sonne/xy/**/*.js"

# Limit concurrency to one workflow per branch and one per pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  setup-job:
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.OPTIMISM_NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

  vaop-test:
    needs: [setup-job]
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.OPTIMISM_NODE_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup-env

      - name: Running Compound XY strategy for VAOP pool
        run: npm test -- --scope vesper-strategies -- test/optimism/sonne/xy/vesper/vaop.spec.js